### ISSUE TITLE
how to train the raw data(unit16) to jpg without quality loss

### ISSUE THREAD

**Issue by zener90818** [sjmoran/CURL#16]
Hi,
Thanks for your great work! I train my own datasets with your codes,  the datasets is collected from Canon cameras(CR2 format). i have three questions：
1. To toning the raw image to the wanted color,  i normalize the  raw data(uint16)  to float32 with 2**14-1.   
`input_img = util.ImageProcessing.load_image(self.data_dict[idx]['input_img'], normaliser=2**14 - 1)`
Can the ImageProcessing method (rgb_to_hsv/rgb_to_lab)  be applied to  image of float32 format without quality loss？
2. the result of test/valid data is blur, how to ensure the sharpness? Is it necessary to transform bayer data to rgb as input? the results are as below，the first image is groundtruth，the second is inference results
![84417100920210626_0018](https://user-images.githubusercontent.com/38679014/127810188-b2284b54-b856-4c8d-afaf-32b6c9fbfd2c.jpg) 
![84417100920210626_0018_VALID_575_10_PSNR_24 722_SSIM_0 848](https://user-images.githubusercontent.com/38679014/127810187-d58562cf-8d07-481a-8469-9408e7b170f4.jpg)
3. Is this network designed for mobile terminal? Regardless of complexity,  Is there a higher accuracy encoder/decoder blocks recommendation?

**Comment by sjmoran** [comment]
Hi, thank you for the interest in our work! 

**To toning the raw image to the wanted color, i normalize the raw data(uint16) to float32 with 2**14-1.
input_img = util.ImageProcessing.load_image(self.data_dict[idx]['input_img'], normaliser=2**14 - 1)
Can the ImageProcessing method (rgb_to_hsv/rgb_to_lab) be applied to image of float32 format without quality loss？**
Yes they can. Just ensure you use the correct normalised (2**14-1) throughout the code.

**the result of test/valid data is blur, how to ensure the sharpness? Is it necessary to transform bayer data to rgb as input? the results are as below，the first image is groundtruth，the second is inference results**
Blur can result if the network output and groundtruth are not pixelwise aligned for the L1/L2 loss. My guess is that pixel-wise misaligned is likely caused by your treatment of the bayer data. You either need to 1) convert the bayer data to an RGB image and use rgb_ted.py backbone network or 2) use the RAW backbone network (raw_ted.py) and handle the mosiac pattern specific to the Canon CR2 format in raw_red.py (raw_ted.py handles RGGB Bayer pattern only currently, but could be adapted to handle Canon CR2).

If you do contribute a new RAW image backbone network for Canon CR2 format please consider creating a pull request to share it to this codebase for CURL.
