### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/curl_validpsnr_23.073045286204017_validloss_0.0701291635632515_testpsnr_23.584083321292365_testloss_0.061363041400909424_epoch_510_model.pt'

### ISSUE THREAD

**Issue by BhavyaSoni31** [sjmoran/CURL#17]
when trying to run command described in readme for pre trained model evaluation I got this error.
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/curl_validpsnr_23.073045286204017_validloss_0.0701291635632515_testpsnr_23.584083321292365_testloss_0.061363041400909424_epoch_510_model.pt'

**Comment by BhavyaSoni31** [comment]
After correcting the path I get this error :- 
File "main.py", line 134, in main
    net.eval()
AttributeError: 'dict' object has no attribute 'eval'

**Comment by sjmoran** [comment]
Hi, the error is due to your inference directory structure. Make sure it looks like the attached screenshots and the content of the images_inference.txt are as shown. 

![directory_structure](https://user-images.githubusercontent.com/10158075/128228522-a2c6e620-8928-421f-97af-bebb741789d4.png)

![images_inference file content](https://user-images.githubusercontent.com/10158075/128228451-c8d728d9-c84e-40bc-9a0b-9ff3b2bcfdb7.png)
