### ISSUE TITLE
Doubt about results

### ISSUE THREAD

**Issue by abetancordelrosario** [sjmoran/CURL#35]
I am picking up the work of a former coworker and I watched that he got this result using Samsung dataset with the adobe pre-trained model.

![Captura de pantalla 2023-01-18 120050](https://user-images.githubusercontent.com/72502267/213166315-72a245f3-75f5-4ee2-b95e-fecdf6fdcd71.png)

But when I test with the same dataset and model I get the next result.

![2_TEST_1_1_PSNR_24 708_SSIM_0 903](https://user-images.githubusercontent.com/72502267/213166564-4b0a709d-2954-4419-8cea-195fddd90b9c.jpg)

I want to know if the artifacts in the first image are normal or if he made a mistake converting the images from RAW to PNG.

Thank you in advance.

**Comment by sjmoran** [comment]
The artefacts are not normal. I suspect there could be a mistake in the conversion from RAW to PNG. Please the closed (resolved) comments in this repo for guidance.

**Comment by abetancordelrosario** [comment]
Thank you for your prompt response

We have noticed that these artifacts appear when decreasing the size of the image, we would like to know if it is normal and the reason why they occur.

Thank you in advance.

**Comment by sjmoran** [comment]
Firstly, the adobe pre-trained model is trained on RGB input, not RAW. Are you using RAW directly as input to the model? If so 1) the pre-trained model is not for RAW data and 2) you are using the raw_ted.py model, you need to be careful when cropping or resizing RAW so that the crop or resize adheres to the Bayer pattern boundaries. If, however, you are using PNG as input (and hence using the rgb_ted.py model) - how do you go from RAW to PNG for Samsung (as this is a RAW dataset), and how do you then resize the images? Please let me know.

**Comment by sjmoran** [comment]
Closing due to a lack of activity.
